Add pagination to `GET Package` endpoint
vipyrsec/dragonfly-mainframe pull request #284
Opened 2024-07-15 16:04 UTC by BruDriguezz

Closes #91

2024-08-03 20:09 UTC, jonathan-d-zhang requested changes
This change will cause the response model of the endpoint to change, right? have you made sure that bot will not break because of this?

2024-08-03 20:09 UTC, jonathan-d-zhang commented on src/mainframe/endpoints/package.py
> +        log.info("Package info queried")
```suggestion
```

2024-08-11 13:58 UTC, jonathan-d-zhang approved these changes
lgtm

2024-08-23 12:36 UTC, jonathan-d-zhang submitted a review, later dismissed

2024-08-24 00:31 UTC, jonathan-d-zhang submitted a review, later dismissed

2024-10-10 06:15 UTC, Robin5605 approved these changes
pretty much exactly what i was going for, thanks!

2024-10-10 06:15 UTC, Robin5605 commented on src/mainframe/endpoints/package.py
> +        if page is not None and size is not None:
```suggestion
        if page and size:
```

2024-10-12 19:24 UTC, import-pandas-as-numpy approved these changes

2024-10-19 00:14 UTC, merged